// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/incident/incident.proto

package incidentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ContainerIssue represents a failure or abnormal state detected
// in a specific container within a Pod.
type ContainerIssue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Container     string                 `protobuf:"bytes,1,opt,name=container,proto3" json:"container,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerIssue) Reset() {
	*x = ContainerIssue{}
	mi := &file_proto_incident_incident_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerIssue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerIssue) ProtoMessage() {}

func (x *ContainerIssue) ProtoReflect() protoreflect.Message {
	mi := &file_proto_incident_incident_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerIssue.ProtoReflect.Descriptor instead.
func (*ContainerIssue) Descriptor() ([]byte, []int) {
	return file_proto_incident_incident_proto_rawDescGZIP(), []int{0}
}

func (x *ContainerIssue) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

func (x *ContainerIssue) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// IncidentReport describes a detected Pod failure event produced by the Officer.
// It contains metadata about the Pod, its current state, and any container-level issues.
type IncidentReport struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PodName   string                 `protobuf:"bytes,2,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	Namespace string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Phase     string                 `protobuf:"bytes,4,opt,name=phase,proto3" json:"phase,omitempty"`
	Reason    string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	// container_issues lists detected runtime issues for containers in the Pod.
	ContainerIssues []*ContainerIssue `protobuf:"bytes,6,rep,name=container_issues,json=containerIssues,proto3" json:"container_issues,omitempty"`
	// logs contains a limited snapshot of relevant Pod logs.
	Logs          []string `protobuf:"bytes,7,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncidentReport) Reset() {
	*x = IncidentReport{}
	mi := &file_proto_incident_incident_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncidentReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncidentReport) ProtoMessage() {}

func (x *IncidentReport) ProtoReflect() protoreflect.Message {
	mi := &file_proto_incident_incident_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncidentReport.ProtoReflect.Descriptor instead.
func (*IncidentReport) Descriptor() ([]byte, []int) {
	return file_proto_incident_incident_proto_rawDescGZIP(), []int{1}
}

func (x *IncidentReport) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *IncidentReport) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *IncidentReport) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *IncidentReport) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *IncidentReport) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *IncidentReport) GetContainerIssues() []*ContainerIssue {
	if x != nil {
		return x.ContainerIssues
	}
	return nil
}

func (x *IncidentReport) GetLogs() []string {
	if x != nil {
		return x.Logs
	}
	return nil
}

// Ack represents a simple acknowledgment response returned by the API server.
// It indicates whether the incident was successfully received and forwarded.
type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_proto_incident_incident_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_proto_incident_incident_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_proto_incident_incident_proto_rawDescGZIP(), []int{2}
}

func (x *Ack) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_incident_incident_proto protoreflect.FileDescriptor

const file_proto_incident_incident_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/incident/incident.proto\x12\bincident\"F\n" +
	"\x0eContainerIssue\x12\x1c\n" +
	"\tcontainer\x18\x01 \x01(\tR\tcontainer\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\xe0\x01\n" +
	"\x0eIncidentReport\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bpod_name\x18\x02 \x01(\tR\apodName\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x14\n" +
	"\x05phase\x18\x04 \x01(\tR\x05phase\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\x12C\n" +
	"\x10container_issues\x18\x06 \x03(\v2\x18.incident.ContainerIssueR\x0fcontainerIssues\x12\x12\n" +
	"\x04logs\x18\a \x03(\tR\x04logs\"\x1f\n" +
	"\x03Ack\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2L\n" +
	"\x0fIncidentService\x129\n" +
	"\x0eReportIncident\x12\x18.incident.IncidentReport\x1a\r.incident.AckB+Z)github.com/ghdrope/court/proto/incidentpbb\x06proto3"

var (
	file_proto_incident_incident_proto_rawDescOnce sync.Once
	file_proto_incident_incident_proto_rawDescData []byte
)

func file_proto_incident_incident_proto_rawDescGZIP() []byte {
	file_proto_incident_incident_proto_rawDescOnce.Do(func() {
		file_proto_incident_incident_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_incident_incident_proto_rawDesc), len(file_proto_incident_incident_proto_rawDesc)))
	})
	return file_proto_incident_incident_proto_rawDescData
}

var file_proto_incident_incident_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_incident_incident_proto_goTypes = []any{
	(*ContainerIssue)(nil), // 0: incident.ContainerIssue
	(*IncidentReport)(nil), // 1: incident.IncidentReport
	(*Ack)(nil),            // 2: incident.Ack
}
var file_proto_incident_incident_proto_depIdxs = []int32{
	0, // 0: incident.IncidentReport.container_issues:type_name -> incident.ContainerIssue
	1, // 1: incident.IncidentService.ReportIncident:input_type -> incident.IncidentReport
	2, // 2: incident.IncidentService.ReportIncident:output_type -> incident.Ack
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_incident_incident_proto_init() }
func file_proto_incident_incident_proto_init() {
	if File_proto_incident_incident_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_incident_incident_proto_rawDesc), len(file_proto_incident_incident_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_incident_incident_proto_goTypes,
		DependencyIndexes: file_proto_incident_incident_proto_depIdxs,
		MessageInfos:      file_proto_incident_incident_proto_msgTypes,
	}.Build()
	File_proto_incident_incident_proto = out.File
	file_proto_incident_incident_proto_goTypes = nil
	file_proto_incident_incident_proto_depIdxs = nil
}
