// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/incident/incident.proto

package incidentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ContainerIssue represents a failure or abnormal state detected
// in a specific container within a Pod.
type ContainerIssue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// container is the name of the container within the Pod.
	Container string `protobuf:"bytes,1,opt,name=container,proto3" json:"container,omitempty"`
	// reason is the raw Kubernetes termination reason
	Reason string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	// logs contains a snapshot of container logs relevant
	// to the failure condition.
	Logs          []string `protobuf:"bytes,3,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerIssue) Reset() {
	*x = ContainerIssue{}
	mi := &file_proto_incident_incident_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerIssue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerIssue) ProtoMessage() {}

func (x *ContainerIssue) ProtoReflect() protoreflect.Message {
	mi := &file_proto_incident_incident_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerIssue.ProtoReflect.Descriptor instead.
func (*ContainerIssue) Descriptor() ([]byte, []int) {
	return file_proto_incident_incident_proto_rawDescGZIP(), []int{0}
}

func (x *ContainerIssue) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

func (x *ContainerIssue) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ContainerIssue) GetLogs() []string {
	if x != nil {
		return x.Logs
	}
	return nil
}

// K8sEvent represents a Kubernetes event associated with the Pod.
//
// These events provide primary diagnostic context for the incident
// and are used to understand cluster-level state transitions.
type K8SEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// type is the event type
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// reason is the Kubernetes event reason
	Reason string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	// message is the human-readable event description.
	Message       string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *K8SEvent) Reset() {
	*x = K8SEvent{}
	mi := &file_proto_incident_incident_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *K8SEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*K8SEvent) ProtoMessage() {}

func (x *K8SEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_incident_incident_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use K8SEvent.ProtoReflect.Descriptor instead.
func (*K8SEvent) Descriptor() ([]byte, []int) {
	return file_proto_incident_incident_proto_rawDescGZIP(), []int{1}
}

func (x *K8SEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *K8SEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *K8SEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// IncidentReport is the representation of a detected Pod failure
// produced by the Officer component.
//
// It is the single source of a Kubernetes workload failure.
type IncidentReport struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id uniquely identifies the incident event.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// cluster is the name of the Kubernetes cluster where the Pod ran.
	Cluster string `protobuf:"bytes,2,opt,name=cluster,proto3" json:"cluster,omitempty"`
	// namespace is the Kubernetes namespace of the Pod.
	Namespace string `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// pod is the name of the Kubernetes Pod that failed.
	Pod string `protobuf:"bytes,4,opt,name=pod,proto3" json:"pod,omitempty"`
	// events contains Kubernetes events related to the Pod lifecycle
	// and failure context.
	Events []*K8SEvent `protobuf:"bytes,5,rep,name=events,proto3" json:"events,omitempty"`
	// container_issues contains detected issues at container level.
	ContainerIssues []*ContainerIssue `protobuf:"bytes,6,rep,name=container_issues,json=containerIssues,proto3" json:"container_issues,omitempty"`
	// prosecutor_commentary is filled by prosecutor after the initial
	// incident creation.
	ProsecutorCommentary string `protobuf:"bytes,7,opt,name=prosecutor_commentary,json=prosecutorCommentary,proto3" json:"prosecutor_commentary,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *IncidentReport) Reset() {
	*x = IncidentReport{}
	mi := &file_proto_incident_incident_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncidentReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncidentReport) ProtoMessage() {}

func (x *IncidentReport) ProtoReflect() protoreflect.Message {
	mi := &file_proto_incident_incident_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncidentReport.ProtoReflect.Descriptor instead.
func (*IncidentReport) Descriptor() ([]byte, []int) {
	return file_proto_incident_incident_proto_rawDescGZIP(), []int{2}
}

func (x *IncidentReport) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *IncidentReport) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

func (x *IncidentReport) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *IncidentReport) GetPod() string {
	if x != nil {
		return x.Pod
	}
	return ""
}

func (x *IncidentReport) GetEvents() []*K8SEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *IncidentReport) GetContainerIssues() []*ContainerIssue {
	if x != nil {
		return x.ContainerIssues
	}
	return nil
}

func (x *IncidentReport) GetProsecutorCommentary() string {
	if x != nil {
		return x.ProsecutorCommentary
	}
	return ""
}

// Ack represents a simple acknowledgment returned by the Archive service.
//
// It indicates whether the incident was successfully received and persisted.
type Ack struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// success indicates whether the operation completed successfully.
	Success       bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_proto_incident_incident_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_proto_incident_incident_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_proto_incident_incident_proto_rawDescGZIP(), []int{3}
}

func (x *Ack) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_incident_incident_proto protoreflect.FileDescriptor

const file_proto_incident_incident_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/incident/incident.proto\x12\bincident\"Z\n" +
	"\x0eContainerIssue\x12\x1c\n" +
	"\tcontainer\x18\x01 \x01(\tR\tcontainer\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x12\n" +
	"\x04logs\x18\x03 \x03(\tR\x04logs\"P\n" +
	"\bK8sEvent\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x90\x02\n" +
	"\x0eIncidentReport\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acluster\x18\x02 \x01(\tR\acluster\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x10\n" +
	"\x03pod\x18\x04 \x01(\tR\x03pod\x12*\n" +
	"\x06events\x18\x05 \x03(\v2\x12.incident.K8sEventR\x06events\x12C\n" +
	"\x10container_issues\x18\x06 \x03(\v2\x18.incident.ContainerIssueR\x0fcontainerIssues\x123\n" +
	"\x15prosecutor_commentary\x18\a \x01(\tR\x14prosecutorCommentary\"\x1f\n" +
	"\x03Ack\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2Q\n" +
	"\x0eArchiveService\x12?\n" +
	"\x14ReceiveStoreIncident\x12\x18.incident.IncidentReport\x1a\r.incident.AckB+Z)github.com/ghdrope/court/proto/incidentpbb\x06proto3"

var (
	file_proto_incident_incident_proto_rawDescOnce sync.Once
	file_proto_incident_incident_proto_rawDescData []byte
)

func file_proto_incident_incident_proto_rawDescGZIP() []byte {
	file_proto_incident_incident_proto_rawDescOnce.Do(func() {
		file_proto_incident_incident_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_incident_incident_proto_rawDesc), len(file_proto_incident_incident_proto_rawDesc)))
	})
	return file_proto_incident_incident_proto_rawDescData
}

var file_proto_incident_incident_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_incident_incident_proto_goTypes = []any{
	(*ContainerIssue)(nil), // 0: incident.ContainerIssue
	(*K8SEvent)(nil),       // 1: incident.K8sEvent
	(*IncidentReport)(nil), // 2: incident.IncidentReport
	(*Ack)(nil),            // 3: incident.Ack
}
var file_proto_incident_incident_proto_depIdxs = []int32{
	1, // 0: incident.IncidentReport.events:type_name -> incident.K8sEvent
	0, // 1: incident.IncidentReport.container_issues:type_name -> incident.ContainerIssue
	2, // 2: incident.ArchiveService.ReceiveStoreIncident:input_type -> incident.IncidentReport
	3, // 3: incident.ArchiveService.ReceiveStoreIncident:output_type -> incident.Ack
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_incident_incident_proto_init() }
func file_proto_incident_incident_proto_init() {
	if File_proto_incident_incident_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_incident_incident_proto_rawDesc), len(file_proto_incident_incident_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_incident_incident_proto_goTypes,
		DependencyIndexes: file_proto_incident_incident_proto_depIdxs,
		MessageInfos:      file_proto_incident_incident_proto_msgTypes,
	}.Build()
	File_proto_incident_incident_proto = out.File
	file_proto_incident_incident_proto_goTypes = nil
	file_proto_incident_incident_proto_depIdxs = nil
}
