// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: proto/incident/incident.proto

package incidentpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ArchiveService_ReceiveStoreIncident_FullMethodName = "/incident.ArchiveService/ReceiveStoreIncident"
)

// ArchiveServiceClient is the client API for ArchiveService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ArchiveService is the ingestion endpoint for IncidentReports.
//
// It receives incidents directly from the Officer component and is responsible
// for persistence, indexing, and downstream processing.
type ArchiveServiceClient interface {
	// ReceiveStoreIncident receives a fully-formed IncidentReport from the Officer
	// and persists it into the Archive system.
	ReceiveStoreIncident(ctx context.Context, in *IncidentReport, opts ...grpc.CallOption) (*Ack, error)
}

type archiveServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewArchiveServiceClient(cc grpc.ClientConnInterface) ArchiveServiceClient {
	return &archiveServiceClient{cc}
}

func (c *archiveServiceClient) ReceiveStoreIncident(ctx context.Context, in *IncidentReport, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, ArchiveService_ReceiveStoreIncident_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArchiveServiceServer is the server API for ArchiveService service.
// All implementations must embed UnimplementedArchiveServiceServer
// for forward compatibility.
//
// ArchiveService is the ingestion endpoint for IncidentReports.
//
// It receives incidents directly from the Officer component and is responsible
// for persistence, indexing, and downstream processing.
type ArchiveServiceServer interface {
	// ReceiveStoreIncident receives a fully-formed IncidentReport from the Officer
	// and persists it into the Archive system.
	ReceiveStoreIncident(context.Context, *IncidentReport) (*Ack, error)
	mustEmbedUnimplementedArchiveServiceServer()
}

// UnimplementedArchiveServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedArchiveServiceServer struct{}

func (UnimplementedArchiveServiceServer) ReceiveStoreIncident(context.Context, *IncidentReport) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method ReceiveStoreIncident not implemented")
}
func (UnimplementedArchiveServiceServer) mustEmbedUnimplementedArchiveServiceServer() {}
func (UnimplementedArchiveServiceServer) testEmbeddedByValue()                        {}

// UnsafeArchiveServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ArchiveServiceServer will
// result in compilation errors.
type UnsafeArchiveServiceServer interface {
	mustEmbedUnimplementedArchiveServiceServer()
}

func RegisterArchiveServiceServer(s grpc.ServiceRegistrar, srv ArchiveServiceServer) {
	// If the following call panics, it indicates UnimplementedArchiveServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ArchiveService_ServiceDesc, srv)
}

func _ArchiveService_ReceiveStoreIncident_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IncidentReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArchiveServiceServer).ReceiveStoreIncident(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArchiveService_ReceiveStoreIncident_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArchiveServiceServer).ReceiveStoreIncident(ctx, req.(*IncidentReport))
	}
	return interceptor(ctx, in, info, handler)
}

// ArchiveService_ServiceDesc is the grpc.ServiceDesc for ArchiveService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ArchiveService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "incident.ArchiveService",
	HandlerType: (*ArchiveServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReceiveStoreIncident",
			Handler:    _ArchiveService_ReceiveStoreIncident_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/incident/incident.proto",
}
