apiVersion: v1
kind: Pod
metadata:
  name: pod-fail-exemplo2
  annotations:
    court.dev/repository: https://github.com/ghdrope/court
spec:
  restartPolicy: Never
  containers:
    - name: app1
      image: busybox:1.36
      command:
        - /bin/sh
        - -c
        - |
          echo "Iniciando aplicação..."
          echo "Processando dados..."
          sleep 5
          echo "app1: Algo deu errado!"
          echo "app1: Algo deu errado!"
          echo "app1: Algo deu errado!"
          sleep 100
          exit 0
    - name: app2
      image: busybox:1.36
      command:
        - /bin/sh
        - -c
        - |
          echo "Iniciando aplicação..."
          echo "Processando dados..."
          sleep 5
          echo "app2: Algo deu errado!"
          echo "app2: Algo deu errado!"
          echo "app2: Algo deu errado!"
          sleep 100
          exit 0