/*
Copyright 2026 Pedro Cozinheiro.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package incident

import v1 "k8s.io/api/core/v1"

// IncidentReport represents a structured description of a pod failure.
// capturing essential metadata and runtime context for downstream processing.
type IncidentReport struct {
	// ID uniquely identifies this incident event.
	// It is generated by the Officer and used for tracking across services.
	ID string

	PodName   string
	Namespace string
	Phase     v1.PodPhase
	Reason    string

	// ContainerIssues contains detected issues at the container level,
	// such as CrashLoopBackOff or OOMKilled states.
	ContainerIssues []ContainerIssue

	// Logs contains a limited snapshot of relevant pod logs.
	// This is intentionally bounded to avoid large payloads.
	Logs []string
}

// ContainerIssue represents a failure or abnormal state detected
// in a specific container within a pod.
type ContainerIssue struct {
	Container string
	Reason    string
}
