apiVersion: v1
kind: ServiceAccount
metadata:
  name: officer
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: court
    app.kubernetes.io/component: officer
    {{- include "court.labels" . | nindent 4 }}

# Dedicated ServiceAccount for the officer controller.
# Required to attach RBAC permissions for Kubernetes API access.
