apiVersion: v2
name: court
description: Helm chart for deploying Court

type: application

version: 0.2.0 # Chart version (increment on ANY chart/template change)
appVersion: "0.0" # Change when new minor of court

keywords:
  - court
  - kubernetes

maintainers:
  - name: Pedro Cozinheiro
    email: 0coasts-gearing@icloud.com
    url: https://github.com/ghdrope

home: https://github.com/ghdrope/court
sources:
  - https://github.com/ghdrope/court