/*
Copyright 2026 Pedro Cozinheiro.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package court

import (
	"context"
	"fmt"
	"net/url"
	"strings"

	"github.com/ghdrope/court/internal/incident"
)

// createGitHubIssue builds and sends the issue to GitHub.
//
// It uses the IncidentReport GitHubRepoURL to determine the target repository.
// If the repository cannot be resolved, issue creation fails.
func (s *Service) createGitHubIssue(ctx context.Context, inc *incident.IncidentReport) (string, error) {

	if s.GitHub == nil {
		return "", fmt.Errorf("github client is not configured")
	}

	if inc.GitHubRepoURL == "" {
		return "", fmt.Errorf("missing GitHubRepoURL on incident")
	}

	owner, repo, err := parseGitHubRepo(inc.GitHubRepoURL)
	if err != nil {
		return "", fmt.Errorf("invalid repository url: %w", err)
	}

	title := fmt.Sprintf(
		"🚨 %s failed (%s) — %s/%s",
		inc.Pod,
		extractPrimaryReason(inc),
		inc.Cluster,
		inc.Namespace,
	)

	body := buildIssueBody(inc)

	return s.GitHub.CreateIssue(ctx, owner, repo, title, body)
}

// parseGitHubRepo extracts owner/repo from a GitHub URL.
func parseGitHubRepo(raw string) (string, string, error) {
	u, err := url.Parse(raw)
	if err != nil {
		return "", "", err
	}

	parts := strings.Split(strings.Trim(u.Path, "/"), "/")
	if len(parts) < 2 {
		return "", "", fmt.Errorf("invalid github repo path")
	}

	return parts[0], parts[1], nil
}

// buildIssueBody formats the GitHub issue content.
//
// Keep in mind the output string must remain optimized for:
//   - Human readability
//   - Machine parsing (LLMs like GitHub Copilot)
//   - Actionability (clear debugging steps)
func buildIssueBody(inc *incident.IncidentReport) string {

	// --- Events (prioritize warnings) ---
	var warnings []string
	var normals []string

	for _, e := range inc.Events {
		line := fmt.Sprintf(
			"- [%s] %s: %s",
			e.Type,
			e.Reason,
			e.Message,
		)

		if strings.ToLower(e.Type) == "warning" {
			warnings = append(warnings, line)
		} else {
			normals = append(normals, line)
		}
	}

	var eventSections []string

	if len(warnings) > 0 {
		eventSections = append(eventSections,
			"### Warnings\n"+strings.Join(warnings, "\n"))
	}

	if len(normals) > 0 {
		eventSections = append(eventSections,
			"### Normal Events\n"+strings.Join(normals, "\n"))
	}

	events := joinOrFallback(eventSections)

	// --- Container issues ---
	var issues []string

	for _, i := range inc.ContainerIssues {

		var logs string

		if len(i.Logs) > 0 {
			max := 10
			truncated := len(i.Logs) > max

			limit := max
			if len(i.Logs) < max {
				limit = len(i.Logs)
			}

			logs = strings.Join(i.Logs[:limit], "\n")

			if truncated {
				logs += "\n... (truncated)"
			}
		}

		entry := fmt.Sprintf(
			"### Container `%s`\n"+
				"- Image: `%s`\n"+
				"- Failure Reason: `%s`\n\n"+
				"#### Logs\n"+
				"```bash\n%s\n```",
			i.Container,
			i.ImageName,
			i.Reason,
			formatLogs(logs),
		)

		issues = append(issues, entry)
	}

	return fmt.Sprintf(`
## 🚨 Automated Incident Report

This issue was automatically generated by **[Court](https://github.com/ghdrope/court)** based on a detected runtime failure.

---

## 📌 Summary

A failure was detected in a Kubernetes workload.  
This issue contains diagnostic data to help identify root cause and guide remediation.

---

## 🧭 Environment

- **Cluster:** %s
- **Namespace:** %s
- **Pod:** %s

---

## ⚠️ Failure Signals

%s

---

## 📦 Container Analysis

%s

---

## 🧩 Potential Root Cause Signals

- Primary failure signal: %s
- Failures may indicate crash loops, misconfiguration, missing dependencies, or resource exhaustion
- Inspect logs for application-level errors

---

## 🧠 Suggested Investigation

Please review the following:

1. Container exit reason and logs
2. Recent changes to the workload (image, config, deploys)
3. Dependency availability (external services, databases, APIs)
4. Resource constraints (CPU, memory, limits)
5. Kubernetes events for scheduling or runtime errors

---

## 🤖 Copilot Hint

You can use GitHub Copilot Chat to analyze this issue and propose a fix:

- Ask: *"What is causing this failure?"*
- Ask: *"Propose a fix based on these logs"*
- Ask: *"Generate a patch or PR to prevent this crash"*

---

_This issue was generated automatically by [Court](https://github.com/ghdrope/court)._
`,
		inc.Cluster,
		inc.Namespace,
		inc.Pod,
		events,
		joinOrFallback(issues),
		extractPrimaryReason(inc),
	)
}

// extractPrimaryReason returns the most relevant failure reason
// from the incident, typically the first container issue.
func extractPrimaryReason(inc *incident.IncidentReport) string {
	if len(inc.ContainerIssues) > 0 {
		if inc.ContainerIssues[0].Reason != "" {
			return inc.ContainerIssues[0].Reason
		}
	}
	return "unknown"
}

// joinOrFallback ensures empty sections are still readable.
func joinOrFallback(items []string) string {
	if len(items) == 0 {
		return "_No data available_"
	}
	return strings.Join(items, "\n\n")
}

// formatLogs ensures logs render correctly inside Markdown code blocks.
func formatLogs(logs string) string {
	// ensures logs are safe inside fenced code block
	logs = strings.TrimSpace(logs)

	if logs == "" {
		return "<no logs available>"
	}

	return logs
}
