apiVersion: v1
kind: Secret
metadata:
  name: {{ default "archive-secret" .Values.archive.auth.existingSecret }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: archive
    {{- include "court.labels" . | nindent 4 }}

type: Opaque

# Stores PostgreSQL credentials.
stringData:
  POSTGRES_PASSWORD: {{ .Values.archive.auth.password | quote }}
  