// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/archive/archive.proto

package archivepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StoreIncidentRequest contains a full incident report payload
type StoreIncidentRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EventId         string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	PodName         string                 `protobuf:"bytes,2,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	Namespace       string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Phase           string                 `protobuf:"bytes,4,opt,name=phase,proto3" json:"phase,omitempty"`
	Reason          string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	ContainerIssues []*ContainerIssue      `protobuf:"bytes,6,rep,name=container_issues,json=containerIssues,proto3" json:"container_issues,omitempty"`
	Logs            []string               `protobuf:"bytes,7,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StoreIncidentRequest) Reset() {
	*x = StoreIncidentRequest{}
	mi := &file_proto_archive_archive_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreIncidentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreIncidentRequest) ProtoMessage() {}

func (x *StoreIncidentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_archive_archive_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreIncidentRequest.ProtoReflect.Descriptor instead.
func (*StoreIncidentRequest) Descriptor() ([]byte, []int) {
	return file_proto_archive_archive_proto_rawDescGZIP(), []int{0}
}

func (x *StoreIncidentRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *StoreIncidentRequest) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *StoreIncidentRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *StoreIncidentRequest) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *StoreIncidentRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *StoreIncidentRequest) GetContainerIssues() []*ContainerIssue {
	if x != nil {
		return x.ContainerIssues
	}
	return nil
}

func (x *StoreIncidentRequest) GetLogs() []string {
	if x != nil {
		return x.Logs
	}
	return nil
}

// ContainerIssue represents container-level failure details
type ContainerIssue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Container     string                 `protobuf:"bytes,1,opt,name=container,proto3" json:"container,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerIssue) Reset() {
	*x = ContainerIssue{}
	mi := &file_proto_archive_archive_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerIssue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerIssue) ProtoMessage() {}

func (x *ContainerIssue) ProtoReflect() protoreflect.Message {
	mi := &file_proto_archive_archive_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerIssue.ProtoReflect.Descriptor instead.
func (*ContainerIssue) Descriptor() ([]byte, []int) {
	return file_proto_archive_archive_proto_rawDescGZIP(), []int{1}
}

func (x *ContainerIssue) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

func (x *ContainerIssue) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type StoreIncidentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreIncidentResponse) Reset() {
	*x = StoreIncidentResponse{}
	mi := &file_proto_archive_archive_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreIncidentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreIncidentResponse) ProtoMessage() {}

func (x *StoreIncidentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_archive_archive_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreIncidentResponse.ProtoReflect.Descriptor instead.
func (*StoreIncidentResponse) Descriptor() ([]byte, []int) {
	return file_proto_archive_archive_proto_rawDescGZIP(), []int{2}
}

func (x *StoreIncidentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_archive_archive_proto protoreflect.FileDescriptor

const file_proto_archive_archive_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/archive/archive.proto\x12\n" +
	"archive.v1\"\xf3\x01\n" +
	"\x14StoreIncidentRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x19\n" +
	"\bpod_name\x18\x02 \x01(\tR\apodName\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x14\n" +
	"\x05phase\x18\x04 \x01(\tR\x05phase\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\x12E\n" +
	"\x10container_issues\x18\x06 \x03(\v2\x1a.archive.v1.ContainerIssueR\x0fcontainerIssues\x12\x12\n" +
	"\x04logs\x18\a \x03(\tR\x04logs\"F\n" +
	"\x0eContainerIssue\x12\x1c\n" +
	"\tcontainer\x18\x01 \x01(\tR\tcontainer\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"/\n" +
	"\x15StoreIncidentResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2f\n" +
	"\x0eArchiveService\x12T\n" +
	"\rStoreIncident\x12 .archive.v1.StoreIncidentRequest\x1a!.archive.v1.StoreIncidentResponseB2Z0github.com/ghdrope/court/proto/archive;archivepbb\x06proto3"

var (
	file_proto_archive_archive_proto_rawDescOnce sync.Once
	file_proto_archive_archive_proto_rawDescData []byte
)

func file_proto_archive_archive_proto_rawDescGZIP() []byte {
	file_proto_archive_archive_proto_rawDescOnce.Do(func() {
		file_proto_archive_archive_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_archive_archive_proto_rawDesc), len(file_proto_archive_archive_proto_rawDesc)))
	})
	return file_proto_archive_archive_proto_rawDescData
}

var file_proto_archive_archive_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_archive_archive_proto_goTypes = []any{
	(*StoreIncidentRequest)(nil),  // 0: archive.v1.StoreIncidentRequest
	(*ContainerIssue)(nil),        // 1: archive.v1.ContainerIssue
	(*StoreIncidentResponse)(nil), // 2: archive.v1.StoreIncidentResponse
}
var file_proto_archive_archive_proto_depIdxs = []int32{
	1, // 0: archive.v1.StoreIncidentRequest.container_issues:type_name -> archive.v1.ContainerIssue
	0, // 1: archive.v1.ArchiveService.StoreIncident:input_type -> archive.v1.StoreIncidentRequest
	2, // 2: archive.v1.ArchiveService.StoreIncident:output_type -> archive.v1.StoreIncidentResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_archive_archive_proto_init() }
func file_proto_archive_archive_proto_init() {
	if File_proto_archive_archive_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_archive_archive_proto_rawDesc), len(file_proto_archive_archive_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_archive_archive_proto_goTypes,
		DependencyIndexes: file_proto_archive_archive_proto_depIdxs,
		MessageInfos:      file_proto_archive_archive_proto_msgTypes,
	}.Build()
	File_proto_archive_archive_proto = out.File
	file_proto_archive_archive_proto_goTypes = nil
	file_proto_archive_archive_proto_depIdxs = nil
}
