name: Dev Docker Court Push

on:
  push:
    branches:
      - development
    paths:
      - 'Makefile'
      - '.github/workflows/**/*'
      - 'cmd/**/*'
      - 'internal/**/*'
      - 'pkg/**/*'
      - 'go.mod'
      - 'go.sum'
      - 'Dockerfile'

jobs:
  call-prod:
    uses: ./.github/workflows/template_dev_docker.yml
    with:
      component: court