/*
Copyright 2026 Pedro Cozinheiro.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package issue

import (
	"fmt"

	"github.com/ghdrope/court/internal/incident"
)

// buildBody generates a detailed Markdown report for the VCS issue.
func buildBody(inc *incident.IncidentReport) string {
	if inc == nil {
		return "## 🚨 Incident report is nil"
	}

	eventsSection := buildEventsSection(inc)
	containersSection := buildContainersSection(inc)

	body := fmt.Sprintf(`
## 🚨 Automated Incident Report

This issue was automatically generated by **[Court](https://github.com/ghdrope/court)** based on a detected runtime failure.

---

## 📌 Summary

A failure was detected in a Kubernetes workload.

You have below full runtime context (Kubernetes events, logs, and metadata). This issue is intended to be **resolved directly by applying a fix in this repository**.

---

## 🧭 Environment

- Cluster: %s
- Namespace: %s
- Pod: %s

---

## ⚠️ Runtime Signals

%s

---

## 📦 Container Analysis

%s

---

## 🧠 AI-Agent Resolution Instructions

You must follow this process strictly:

### 1. Check Kubernetes configuration first
Start by inspecting all Kubernetes-related manifests in this repository:

- .yaml files (Deployments, Pods, Jobs, Services)
- Helm charts or templates
- Any configuration defining this workload

Determine if the root cause is:
- misconfiguration
- missing environment variables
- incorrect image or command
- incorrect dependency configuration

If the issues is found here, **fix the manifest directly**.

---

### 2. If not found in manifests, analyze application code

Search the codebase using the runtime context provided above.

Look specifically for:

- error messages found in logs
- container names (e.g. api, worker)
- function names referenced in stack traces
- file names mentioned implicitly in logs
- variable names or configuration keys
- exceptions (e.g. panic, null pointer, runtime errors)

Infer connections between:
- logs -> source files
- errors -> functions
- configuration -> runtime behavior

---

### 3. Identify root cause

Classify the failure clearly as one of:

- infrastructure / Kubernetes misconfiguration
- missing dependency or service
- application logic bug
- runtime exception or crash
- resource limitation or scheduling issue

---

### 4. Apply the fix

Once the root cause is identified:

- implement the minimal safe fix
- prefer configuration or manifest fixes when possible
- only modify application code if necessary
- ensure the fix fully resolves the failure scenario

---

### FINAL INSTRUCTION

You are not performing analysis only.

You are required to **apply the fix directly in this repository**.

Please proceed and implement the necessary fix.
`,
		inc.Cluster,
		inc.Namespace,
		inc.Pod,
		eventsSection,
		containersSection,
	)

	return body
}
