package issue

import (
	"fmt"
	"strings"

	"github.com/ghdrope/court/internal/incident"
)

// buildBody generates a detailed Markdown report for the VCS issue.
func buildBody(inc *incident.IncidentReport) string {
	if inc == nil {
		return "## 🚨 Incident report is nil"
	}

	// -------------------------
	// EVENTS
	// -------------------------
	var normalEvents []string
	var warningEvents []string

	for _, e := range inc.Events {
		line := fmt.Sprintf("- [%s] %s: %s", e.Type, e.Reason, e.Message)

		if strings.EqualFold(e.Type, "warning") {
			warningEvents = append(warningEvents, line)
		} else {
			normalEvents = append(normalEvents, line)
		}
	}

	eventsSection := "No events available"

	if len(warningEvents) > 0 || len(normalEvents) > 0 {
		var b strings.Builder

		if len(warningEvents) > 0 {
			b.WriteString("### Warnings\n```\n")
			b.WriteString(strings.Join(warningEvents, "\n"))
			b.WriteString("\n```\n\n")
		}

		if len(normalEvents) > 0 {
			b.WriteString("### Events\n```\n")
			b.WriteString(strings.Join(normalEvents, "\n"))
			b.WriteString("\n```")
		}

		eventsSection = b.String()
	}

	// -------------------------
	// CONTAINERS
	// -------------------------
	var containers []string

	if len(inc.ContainerIssues) == 0 {
		containers = append(containers, "_No container issues detected_")
	} else {
		for _, c := range inc.ContainerIssues {
			logs := formatLogs(c.Logs)

			entry := fmt.Sprintf(
				"### Container `%s`\n"+
					"- Image: `%s`\n"+
					"#### Logs\n"+
					"```\n%s\n```",
				c.Container,
				c.ImageName,
				logs,
			)

			containers = append(containers, entry)
		}
	}

	// -------------------------
	// BODY
	// -------------------------
	body := fmt.Sprintf(`
## 🚨 Automated Incident Report

This issue was automatically generated by **[Court](https://github.com/ghdrope/court)** based on a detected runtime failure.

---

## 📌 Summary

A failure was detected in a Kubernetes workload.  
This issue contains diagnostic data to help identify root cause and guide remediation.

---

## 🧭 Environment

- Cluster: %s
- Namespace: %s
- Pod: %s

---

## ⚠️ Failure Signals

%s

---

## 📦 Container Analysis

%s

---

## 🧩 Potential Root Cause Signals

- Likely causes: crash loops, misconfiguration, missing dependencies, resource exhaustion

---

## 🧠 Suggested Investigation

Please review the following:

1. Container exit reason and logs
2. Recent changes to the workload (image, config, deploys)
3. Dependency availability (external services, databases, APIs)
4. Resource constraints (CPU, memory, limits)
5. Kubernetes events for scheduling or runtime errors

`,
		inc.Cluster,
		inc.Namespace,
		inc.Pod,
		eventsSection,
		strings.Join(containers, "\n\n"),
	)

	body += vcsSectionFor(inc)

	body += "\n---\n_This issue was generated automatically by [Court](https://github.com/ghdrope/court)._\n"

	return body
}
