/*
Copyright 2026 Pedro Cozinheiro.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package issue

import (
	"fmt"

	"github.com/ghdrope/court/internal/incident"
)

// buildBody generates a detailed Markdown report for the VCS issue.
func buildBody(inc *incident.IncidentReport) string {
	if inc == nil {
		return "## 🚨 Incident report is nil"
	}

	eventsSection := buildEventsSection(inc)
	containersSection := buildContainersSection(inc)

	body := fmt.Sprintf(`
## 🚨 Automated Incident Report

This issue was automatically generated by **[Court](https://github.com/ghdrope/court)** based on a detected runtime failure.

---

## 📌 Summary

A failure was detected in a Kubernetes workload.  
This issue contains diagnostic data to help identify root cause and guide remediation.

---

## 🧭 Environment

- Cluster: %s
- Namespace: %s
- Pod: %s

---

## ⚠️ Failure Signals

%s

---

## 📦 Container Analysis

%s

---

## 🧩 Potential Root Cause Signals

- Likely causes: crash loops, misconfiguration, missing dependencies, resource exhaustion

---

## 🧠 Suggested Investigation

Please review the following:

1. Container exit reason and logs
2. Recent changes to the workload (image, config, deploys)
3. Dependency availability (external services, databases, APIs)
4. Resource constraints (CPU, memory, limits)
5. Kubernetes events for scheduling or runtime errors

`,
		inc.Cluster,
		inc.Namespace,
		inc.Pod,
		eventsSection,
		containersSection,
	)

	body += vcsSectionFor(inc)

	body += "\n---\n_This issue was generated automatically by [Court](https://github.com/ghdrope/court)._\n"

	return body
}
